name: prod # no importa si ya existe porque va a ser instalado en un prefijo local

dependencies:
  - python=3.7 # pinneado porque es la versión que hay en los workers del cluster
  - pip
  - pandas
  - numpy
  - sqlalchemy
  - cx_Oracle
  - numpy
  - jupyter
  - jupyterlab
  - python-dateutil
  - psycopg2
  - python-dateutil
  - click 
  - pip:
    - typer
    - great_expectations
    - optuna
    - sklearn


# comandos utiles:

# conda env create --prefix ./env -f environment.yml
# conda activate ./env
# conda env update --prefix ./env -f environment.yml --prune
# conda env export --from-history -f environment.yml
